spring.application.name=backend
server.port=6969

spring.data.mongodb.uri=mongodb+srv://lucky:zOJSvpQYEDnA0sjD@event.1o5pj.mongodb.net/?retryWrites=true&w=majority&appName=event
spring.data.mongodb.database=mygrocerylist
